### ISSUE TITLE
Make copy tool easier to use

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-london#737]
Ideally click 'Copy' and then just click straight onto building (without clicking 'copy selected'. Add hints on how to use and check obvious how to click off 'copy'selected'

- [x] Enable the copy checkbox on all fields
- [x] Rename/ fiddle so there is a distinction between "Copy all" and "Copy selected"
- ~~Make it obvious that you can copy verification (but this should be separate from copying fields) - add copy select boxes to the verification buttons themselves~~ new issue #844

**Comment by polly64** [comment]
Justification: 

-allow people the option to focus on a single question e.g liking a building or saying it should be registered as of local significance and then just click across multiple buildings quickly rather than having to enter scroll and tick for each one 

- raises the issue of users having to fill in multiple OSMM polygons associated with a single site/building which is very boring and very slow . 
- 
- it is also linked to problem to analysis. e.g. for 'like' f all polygons are separately liked at the moment for polygons that are linked to a single site/address they will each be recorded as an individual like but not necessarily relate to a building etc. this cannot be easily resolved easily as this is a structural issue to do with OSMasterMap. Needs more discussion

**Comment by matkoniecz** [comment]
possible idea with really ugly mockup:

maybe make buttons more buton-like with at least some border?

(obviously not as ugly as in the quick paint mockup)

![tempsnip](https://user-images.githubusercontent.com/899988/151805051-b8f37e20-a5e9-41ce-8d1e-fd5ceecef23a.png)

**Comment by edwardchalstrey1** [comment]
Ideas:
- Hover tooltip explaining how Copy works

**Comment by matkoniecz** [comment]
![Capture](https://user-images.githubusercontent.com/899988/151806215-49499557-f299-4104-ad98-25557bc819eb.PNG)

**Comment by edwardchalstrey1** [comment]
@matkoniecz did you make some changes already on a branch towards this goal?
