### ISSUE TITLE
Colouring Ukraine

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#795]
Could we set up a Colouring Ukraine platform building on our discussions of using open code in emergency situations.

I don't know whether we might be able to bring together colleagues from the Open data community to help?  using either national mapping footprints if they exist, or a call out to OSM to create new ones from satellite imagery. This might possibly be useful in three ways:

- To provide a public canvas to allow Ukranians having had to flee the country, and struggling with loss of sense of place,  to  feel more connected with their homes by being able to record information on these and their local areas

- To actively celebrate,and show the world, the richness of Ukraine and its cities

- To provide a detailed record of Ukranian buildings and built heritage before the invasion
- and to show the world what has/is being lost

- To support reconstruction, which obviously we all hope will come as soon as possible

https://github.com/colouring-cities/colouring-london/issues/627
https://github.com/colouring-cities/colouring-london/issues/760

**Comment by edwardchalstrey1** [comment]
Hi Polly, I have a few thoughts on this idea:

1. Feel free to disagree, but were we were to go down this route at all, my thoughts are that will would be something to be a no.1 priority, which would be at the expense of Colouring London/Britain - I think it's a great idea potentially, but I'm not sure the impact would be much were this to be something that simply becomes one of the other colouring cities projects, where we need to look for collaborators, as oppose to us doing it ourselves an making it the main focus - in which case it could be more beneficial. It would require a clear vision and we should spend a lot of time asap scoping exactly what we wanted to achieve. I worked on one of the Turing's quick response Covid projects at the start of the pandemic, which was not clear enough it's objectives and felt that a lot of time/effort was wasted as a result. But if you did go that route, and we thought there was some real achievable benefit, maybe I could even try to speak to the REG team about getting myself taken off my other project and working on this 100% (I have no idea if this is realistic/possible however).
2. In terms of the crowdsourcing aspect, I don't think it would be very realistic to get people in Ukraine to provide building info on the website, however, perhaps we could reach out to UK-based Ukrainians (I'm not sure for example if we need everything to be English) to get involved? Or others with intimate knowledge of the pre-invasion infrastructure.
3. Since the key thing here would be the demolition-tracking, the strands of work as I see them would be:
    - Get a Colouring-Ukraine site up and running using the current application code and with map data that we acquire somehow (perhaps Colouring-Kyiv is more realistic)
    - Find people to provide the annotations using the site interface once live, on the basis of what the buildings were like _before_ the invasion
    - In the meantime, develop the demolition tracking feature
    - At some point in the future, presumably when the war is over, ask the annotators to re-annotate the city/country based on the building destruction that has occurred

To be honest, there are probably various additional challenges I have completely overlooked as someone who is relatively new to the project, so I will leave it for others to comment.

**Comment by matkoniecz** [comment]
General note: it would be worth verifying whether something like that would be welcome right now.

It is likely that Ukrainians would prefer to avoid making recent accurate satellite imagery to be public. As it is likely right now they have better info about situation on the ground than Russians (due to familiarity with own area, also I expect that USA/NATO transfers to them imagery from their sources).

The same goes for recent open data.

**Comment by polly64** [comment]
Thanks for comments, I think probably most useful in reconstruction and obviously needs to be set up by those who think it would be useful. Agree as could have negative impact at this stage,  live collection much more suitable to advance for climate emergency.  Most useful thing we can do as you say Ed is to get the open code/interface super easy to use (and tested for Colouring Britain) if required at any stage

**Comment by matkoniecz** [comment]
Should we keep this issue open? Or close it and reopen once (hopefully soon) war stops and main problem is not going to be a blocker.

BTW translation ( #777 ) is likely to be important here.

**Comment by polly64** [comment]
happy to close if you think appropriate
