### ISSUE TITLE
 AGE

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-london#89]
Live to-do list

- [x] Add 'Guesstimate from image' in dropdown (keep expert assessment as option)
- [x] Swap places of ' earliest start date 'and 'latest start date'
- [ ] Add 'copy all' option
- [X] Check Kayaan can add 
- [x]  Address background 'night' colour issue as colours cannot be seen
- [ ] Add pop up text - for historic environment users particularly  that OS footprints won't let you add extension dates but you can add links to info on these in link box
- [x] Add PH source list

Discussion

- Adjust colour key once background black has been addressed
- Polly to ask FR if she can complete post 1940- 64 and 1965-1990 age generation 
- Discuss multiple age issue further colouring-cities/colouring-core#467
- PH to check other subcategories suggested in colouring-cities/colouring-core#208

Colour Key 

 colour key references colouring-cities/colouring-core#525

**Comment by polly64** [comment]
@mdsimpson42 can you check if items above are included ignoring comments on colour

**Comment by mdsimpson42** [comment]
I think so. It's hard to say without more context. I assume the "background 'night' colour issue" was fixed? 

I'd be tempted to automatically close any issues raised before a certain date, unless there's something specific in them that still needs to be done. The interface has been reworked so much in the last year-or-so that it will be hard to keep track.
